// Amazon-Buchungstexte (PayJoe / Amainvoice / Lexoffice / DATEV)
// Quellen:
// - hilfe.payjoe.de/online-haendler/Content/topics_payjoe/zahlungssysteme/amazon.htm
// - fibu-schnittstelle.com (Amazon-Gebühren-USt-Änderung 01.08.2024)
// - Amazon Seller Forum DE Threads
// - Standard SKR03/SKR04 Kontenrahmen
//
// Stand: Mai 2026. Keine Steuerberatung – nur Orientierungshilfe. Final mit StB klären.

export type AmazonCodeCategory =
  | "prefix"          // Haupt-Prefix (AMA-SG, AMA-BG, AUSZ)
  | "service-fee"     // Plattform-/Service-Gebühren (monatlich, abo-artig)
  | "order-fee"       // Per-Order-Gebühren (Verkaufsprovision, Pick-Pack)
  | "advertising"     // PPC / Sponsored Ads
  | "fba"             // FBA-Gebühren (Lager, Inbound, Pick-Pack)
  | "storage"         // Lagergebühren, Long-Term-Storage
  | "refund"          // Kunden-Refund / Storno
  | "reimbursement"   // FBA-Erstattung (verlorene/beschädigte Ware)
  | "chargeback"      // Chargeback / Kreditkarten-Rückbuchung
  | "payout"          // Auszahlung an Bank
  | "reserve"         // Sicherheits-Reserve (gehalten)
  | "epr"             // Verpackungsgesetz / Eco-Contribution
  | "subscription"    // Pro-Account-Abo
  | "vine"            // Vine / Coupon / Deals
  | "tax"             // Tax-bezogen (MarketplaceFacilitatorVAT etc.)
  | "adjustment"      // Korrekturen, Adjustments
  | "other";

export type AmazonCode = {
  code: string;                    // Original-Code aus PayJoe-Auszug
  category: AmazonCodeCategory;
  label: string;                   // Kurze deutsche Beschriftung
  meaning: string;                 // Was passiert hier wirtschaftlich
  sign: "minus" | "plus" | "both"; // Vorzeichen wenn auf Bank/PayJoe-Konto sichtbar
  skr03: string;                   // SKR03-Konto + ggf. Steuerschlüssel
  skr04: string;                   // SKR04-Konto + ggf. Steuerschlüssel
  ust: string;
  bookingHint: string;             // Kurz: wie buchen
  example?: string;                // Beispiel aus echtem Auszug
  popular?: boolean;               // Top-20-Codes die User oft sehen
};

// ============================================================
// HAUPT-PREFIXES (so heißt die Buchung auf der Bank)
// ============================================================

export const PREFIX_CODES: AmazonCode[] = [
  {
    code: "AMA-SG-DE",
    category: "prefix",
    label: "Amazon Servicegebühr DE",
    meaning:
      "Servicegebühren für den deutschen Marketplace (Plattform-Gebühren, FBA-Lager, Werbung, Subscription). Das volle Format ist AMA-SG-DE-CODE wo CODE die konkrete Gebührenart ist (z.B. AMA-SG-DE-MZNFS für AmazonFees, AMA-SG-DE-FBAFees für FBA-Lagerung).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 9 = VSt 19%)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint:
      "Seit 01.08.2024 stellt Amazon EU Sarl Niederlassung Deutschland die Gebühren MIT 19% deutscher USt aus → Vorsteuer abziehbar (Schlüssel 9 in SKR03 / 9 oder 401 lt. PayJoe-Doku). Nicht mehr Reverse Charge!",
    example: "AMA-SG-DE-MZNFS / -45,00 € → Aufwand 3100 (Soll) 37,82 € + VSt 1576 (Soll) 7,18 € an Verbindlichkeiten Amazon",
    popular: true,
  },
  {
    code: "AMA-SG-IT",
    category: "prefix",
    label: "Amazon Servicegebühr Italien",
    meaning:
      "Servicegebühren des italienischen Marketplaces. Vorsicht: bei Verkauf aus IT-Lager → IT-USt-Pflicht. Bei Versand aus DE-Lager nach IT → Reverse Charge möglich (B2B) oder OSS (B2C).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 19 = Reverse Charge §13b UStG)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint:
      "Wenn Amazon AEU mit IT-USt fakturiert: Reverse Charge §13b UStG → §13b-Schlüssel verwenden, USt selbst berechnen + zugleich Vorsteuer abziehen (saldo 0).",
    example: "AMA-SG-IT-MZNFS / -25,00 €",
    popular: true,
  },
  {
    code: "AMA-SG-FR",
    category: "prefix",
    label: "Amazon Servicegebühr Frankreich",
    meaning:
      "Servicegebühren französischer Marketplace. Gleiche Logik wie IT (Reverse Charge oder lokale FR-USt bei FR-Lager).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 19)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint: "Reverse Charge §13b UStG analog AMA-SG-IT.",
    popular: true,
  },
  {
    code: "AMA-SG-ES",
    category: "prefix",
    label: "Amazon Servicegebühr Spanien",
    meaning: "Servicegebühren spanischer Marketplace. Bei ES-Lager: lokale ES-USt-Registrierung nötig.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 19)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint: "Reverse Charge §13b UStG analog AMA-SG-IT.",
  },
  {
    code: "AMA-SG-CO.UK",
    category: "prefix",
    label: "Amazon Servicegebühr UK",
    meaning:
      "Servicegebühren UK-Marketplace. Brexit: UK ist Drittland → Leistungen nach §3a Abs.2 UStG ggf. nicht steuerbar in DE.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 94 = Drittland Dienstleistungseinkauf)",
    skr04: "5900 Fremdleistungen",
    ust: "Drittland steuerfrei",
    bookingHint: "Reverse Charge §13b UStG (Drittland) – analog Reverse Charge mit Schlüssel 94.",
  },
  {
    code: "AMA-SG-NL",
    category: "prefix",
    label: "Amazon Servicegebühr Niederlande",
    meaning: "Servicegebühren NL-Marketplace.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 19)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint: "Reverse Charge §13b UStG.",
  },
  {
    code: "AMA-SG-COM",
    category: "prefix",
    label: "Amazon Servicegebühr USA (.com)",
    meaning:
      "Servicegebühren US-Marketplace. USA = Drittland → in DE nicht steuerbar (sofern Leistung dort verbraucht wird).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 94 Drittland)",
    skr04: "5900 Fremdleistungen",
    ust: "Drittland steuerfrei",
    bookingHint: "Drittland-Eingangsleistung, kein USt-Ausweis.",
  },
  {
    code: "AMA-BG-DE",
    category: "prefix",
    label: "Amazon Bestellgebühr DE",
    meaning:
      "Bestellbezogene Gebühren (Verkaufsprovision pro Bestellung, FBA-Pick-Pack pro Order). Format: AMA-BG-DE-{Bestellnummer}. PayJoe-Foren-Konsens: 'AMA-BG-DE sind Fremdleistungen.'",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 9 = VSt 19%)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint:
      "Wie AMA-SG-DE: seit 08/2024 mit deutscher USt → VSt abziehbar. Alternativ Konto 4760 'Verkaufsprovisionen' falls bevorzugt.",
    example: "AMA-BG-DE-303-1234567-1234567 / -3,45 € (Verkaufsprovision auf 23 € Order)",
    popular: true,
  },
  {
    code: "AMA-BG-IT",
    category: "prefix",
    label: "Amazon Bestellgebühr Italien",
    meaning: "Verkaufsprovision pro IT-Marketplace-Order.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 19)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint: "Reverse Charge §13b UStG.",
  },
  {
    code: "AMA-BG-FR",
    category: "prefix",
    label: "Amazon Bestellgebühr Frankreich",
    meaning: "Verkaufsprovision pro FR-Marketplace-Order.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Steuerschlüssel 19)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint: "Reverse Charge §13b UStG.",
  },
  {
    code: "AUSZ-DE",
    category: "prefix",
    label: "Amazon Auszahlung DE",
    meaning:
      "Auszahlung des deutschen Marketplace-Saldos auf das Bankkonto. Format: AUSZ-DE-{BerichtEndDatum}. KEIN Aufwand und KEIN Erlös – nur Geldtransit (Verschiebung von 'Forderung an Amazon' auf 'Bank').",
    sign: "plus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint:
      "Buchung: Bank (1200) an Geldtransit (1360). Die Erlöse selbst werden separat aus PayJoe pro Order/Settlement-Periode ausgegeben und gegen das Geldtransit-Konto gebucht. Saldo Geldtransit sollte am Periodenende ~0 sein.",
    example: "AUSZ-DE-31052026 / +12.450,00 €",
    popular: true,
  },
  {
    code: "AUSZ-IT",
    category: "prefix",
    label: "Amazon Auszahlung Italien",
    meaning: "Settlement-Auszahlung des italienischen Marketplaces.",
    sign: "plus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Bank an Geldtransit. Wie AUSZ-DE.",
  },
  {
    code: "AUSZ-FR",
    category: "prefix",
    label: "Amazon Auszahlung Frankreich",
    meaning: "Settlement-Auszahlung des französischen Marketplaces.",
    sign: "plus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Bank an Geldtransit.",
  },
];

// ============================================================
// SUB-CODES (Detail-Codes innerhalb AMA-SG-XX-* / AMA-BG-XX-*)
// ============================================================

export const SUB_CODES: AmazonCode[] = [
  // --- Plattform-Gebühren ---
  {
    code: "MZNFS",
    category: "service-fee",
    label: "Amazon Fees (Verkaufsprovision)",
    meaning:
      "Verkaufsprovision (Referral Fee) – meist 8–17% des Verkaufspreises, kategorieabhängig. Plus 0,99 € pro Verkauf wenn Basic-Account.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9 = VSt 19%)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Seit 01.08.2024 mit deutscher USt → Vorsteuer abziehbar.",
    popular: true,
  },
  {
    code: "FBAFees",
    category: "fba",
    label: "FBA Pick & Pack",
    meaning: "Versandgebühr von FBA pro versandter Einheit (Pick, Pack, Versand). Größenabhängig.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Klassische FBA-Pick-Pack-Gebühr. Vorsteuer abziehbar.",
    popular: true,
  },
  {
    code: "FBAPCKPCK",
    category: "fba",
    label: "FBA Pick & Pack (Detail)",
    meaning: "Detailliertere Auflösung der FBA-Pick-&-Pack-Fee.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie FBAFees.",
  },
  {
    code: "FBPRNT",
    category: "fba",
    label: "FBA Per-Unit Fulfillment",
    meaning: "Fulfillment-Fee pro Einheit (alternative Bezeichnung).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand mit VSt 19%.",
  },
  {
    code: "StorFe",
    category: "storage",
    label: "Lagergebühr (Storage Fee)",
    meaning: "Monatliche FBA-Lagergebühr (€/m³). Kann saisonal stark schwanken (Q4 teurer).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9) – alternativ 4210 Mietkosten",
    skr04: "5900 Fremdleistungen – alternativ 6310 Miete",
    ust: "19% VSt-abziehbar",
    bookingHint: "Manche StB buchen Storage als Miete (4210/6310), andere als Fremdleistung (3100/5900). Beides zulässig, nur konsistent halten.",
    popular: true,
  },
  {
    code: "StoRenBi",
    category: "storage",
    label: "Storage Renewal Billing",
    meaning: "Verlängerte Lagergebühr / Long-Term-Storage.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie StorFe.",
  },
  {
    code: "STRGRNW1",
    category: "storage",
    label: "Storage Renewal Korrektur",
    meaning: "Korrektur einer Storage-Renewal-Buchung (kann + oder − sein).",
    sign: "both",
    skr03: "3100 Fremdleistungen (Schlüssel 9) bzw. Erstattung als VSt-Korrektur",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Bei + auf 8400 Sonstige Erträge oder gegen 3100 (Aufwandsminderung).",
  },
  {
    code: "STRGRNWL",
    category: "storage",
    label: "Storage Renewal Reversal",
    meaning: "Stornierung einer Storage-Renewal-Gebühr.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung) – Schlüssel 9 negativ",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung mit VSt-Korrektur.",
  },
  {
    code: "NVNTRYST",
    category: "storage",
    label: "Inventory Storage Overage Fee",
    meaning: "Strafgebühr wenn FBA-Lagerlimit überschritten wird.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie normale Lagergebühr.",
  },
  {
    code: "NVNTRYPL",
    category: "fba",
    label: "Inventory Placement Service Fee",
    meaning: "Gebühr wenn Amazon den Inbound auf 1 Lager statt mehrere verteilt.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand mit VSt 19%.",
  },
  {
    code: "FBNBNDPL",
    category: "fba",
    label: "FBA Inbound Placement",
    meaning: "Inbound-Placement-Service-Fee (neuere Bezeichnung).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie NVNTRYPL.",
  },
  {
    code: "FBNBNDTR",
    category: "fba",
    label: "FBA Inbound Transportation",
    meaning: "Transport-Gebühr für Inbound-Versand (Partnered Carrier).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9) – alternativ 4730 Ausgangsfrachten",
    skr04: "5900 Fremdleistungen – alternativ 6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Manche StB führen das auf einem Frachtkonto (4730/6740). Beides geht.",
  },
  {
    code: "InbTraCh",
    category: "fba",
    label: "Inbound Transportation Charge",
    meaning: "Inbound-Versandgebühr (Variante).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie FBNBNDTR.",
  },
  {
    code: "NBNDTRNS",
    category: "fba",
    label: "Inbound Transportation Fee",
    meaning: "Inbound-Versand alternative Bezeichnung.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie InbTraCh.",
  },

  // --- Werbung / PPC ---
  {
    code: "CoAdv",
    category: "advertising",
    label: "Cost of Advertising (PPC)",
    meaning: "Sponsored-Products / Sponsored-Brands-Werbekosten. PayJoe-Empfehlung: 4600/6603.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten – nicht Fremdleistungen! Eigenes Aufwandskonto, weil oft DATEV-Auswertungen darauf laufen.",
    popular: true,
  },

  // --- Coupons / Deals / Promotions ---
  {
    code: "CPNPRTCP",
    category: "vine",
    label: "Coupon Participation Fee",
    meaning: "Gebühr für Teilnahme an Coupon-Aktionen (60 Cent pro eingelöstem Coupon).",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten – wie CoAdv.",
  },
  {
    code: "CPNPRFRM",
    category: "vine",
    label: "Coupon Performance Based Fee",
    meaning: "Performance-basierte Coupon-Gebühr.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "CPNRDMPT",
    category: "vine",
    label: "Coupon Redemption Fee",
    meaning: "Gebühr beim Einlösen eines Coupons (zusätzlich zur Reduktion).",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "DLPRTCPT",
    category: "vine",
    label: "Deal Participation Fee",
    meaning: "Gebühr für Teilnahme an Lightning-Deals / Best-Deals.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "DLPRFRMN",
    category: "vine",
    label: "Deal Performance Based Fee",
    meaning: "Performance-basierte Deal-Gebühr.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "LighDeFe",
    category: "vine",
    label: "Lightning Deal Fee",
    meaning: "Lightning-Deal-Gebühr (legacy Code).",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "LGHTNNGD",
    category: "vine",
    label: "Lightning Deal Fee (neu)",
    meaning: "Lightning-Deal-Gebühr.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "VNNRLLMN",
    category: "vine",
    label: "Vine Enrollment Fee",
    meaning: "Gebühr für Vine-Programm (Reviews durch Top-Reviewer).",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "RVWNRLLM",
    category: "vine",
    label: "Review Enrollment Fee",
    meaning: "Review-Programm-Anmeldegebühr.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "PRMTNF",
    category: "vine",
    label: "Promotion Fee",
    meaning: "Aktions-/Werbegebühr.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "PRMTNF1",
    category: "vine",
    label: "Promotion Fee (Variante)",
    meaning: "Aktions-/Werbegebühr (alternative Bezeichnung).",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "PRMTNDJS",
    category: "adjustment",
    label: "Promotion Adjustment",
    meaning: "Korrektur einer Promotion-Gebühr (kann + oder − sein).",
    sign: "both",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Bei + Aufwandsminderung, bei − zusätzlicher Aufwand.",
  },

  // --- Subscriptions ---
  {
    code: "SubFe",
    category: "subscription",
    label: "Subscription Fee",
    meaning: "Pro-Account-Abo (39 €/Mon).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9) – alternativ 4920 Beiträge",
    skr04: "5900 Fremdleistungen – alternativ 6815 Beiträge",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wiederkehrendes Abo, kann auch auf Beiträge/Gebühren-Konto. VSt 19%.",
    popular: true,
  },
  {
    code: "SubFeCor",
    category: "subscription",
    label: "Subscription Fee Correction",
    meaning: "Korrektur Subscription-Fee.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Korrekturbuchung, Vorzeichen beachten.",
  },
  {
    code: "SBSCRPTN",
    category: "subscription",
    label: "Subscription Refund (Credit Card)",
    meaning: "Subscription-Refund auf Kreditkarte.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung, gegen Vorsteuer korrigieren.",
  },
  {
    code: "SBSCRPT1",
    category: "subscription",
    label: "Subscription Refund (Balance Adjustment)",
    meaning: "Subscription-Refund über Saldo-Adjustment.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "SBSCRPT2",
    category: "subscription",
    label: "Subscription Reversal",
    meaning: "Storno einer Subscription-Buchung.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },

  // --- Refunds (Kunde bekommt Geld zurück) ---
  {
    code: "AtoZRefu",
    category: "refund",
    label: "A-to-z Guarantee Refund",
    meaning:
      "Käufer hat A-to-z-Garantie genutzt – Amazon erstattet dem Kunden, du verlierst Erlös plus ggf. Gebühren.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen / alternativ 4760 mit Schlüssel 9",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint:
      "Erlösschmälerung – nicht als 'Aufwand' buchen! Mindert deinen Erlös. USt-Korrektur ggf. auf 1776 (umsatzsteuer 19% Rückforderung).",
    popular: true,
  },
  {
    code: "2ZGRNTRC",
    category: "refund",
    label: "A2Z Guarantee Recovery",
    meaning: "Rückforderung einer A-to-z-Erstattung (z.B. wenn Käufer doch zahlt).",
    sign: "plus",
    skr03: "8730 Erlösschmälerungen (Korrektur)",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Aufhebung der A-to-z-Refund-Buchung.",
  },
  {
    code: "RFNDCMMS",
    category: "refund",
    label: "Refund Commission",
    meaning:
      "Bei Refund: Amazon erstattet dir 80% der ursprünglichen Verkaufsprovision zurück (Refund-Commission). 20% behält Amazon als Bearbeitungs-Pauschale.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung, Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Mindert Fremdleistungs-Aufwand. VSt-Korrektur (negative VSt).",
    popular: true,
  },
  {
    code: "RFNDRMBR",
    category: "refund",
    label: "Refund Reimbursal",
    meaning: "Erstattung einer Refund-Gebühr.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "RFNDRTRC",
    category: "refund",
    label: "Refund Retrocharge",
    meaning: "Refund-Rückbelastung.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "GteeClm",
    category: "refund",
    label: "Guarantee Claim",
    meaning: "Garantie-Anspruch des Kunden (vergleichbar A-to-z).",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "GDWLLCNC",
    category: "refund",
    label: "Goodwill Concession",
    meaning: "Kulanz-Erstattung an Kunden.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "FBCSTMRR",
    category: "refund",
    label: "FBA Customer Return",
    meaning: "Kunde retourniert Ware via FBA.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung. Bei Ware: zusätzlich Bestandsbuchung beachten.",
  },
  {
    code: "FBCSTMR1",
    category: "refund",
    label: "FBA Customer Return Per-Unit Fee",
    meaning: "Bearbeitungsgebühr je Retoure (zusätzlich zur Erlös-Korrektur).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand. Eigene Buchung – nicht Teil des Erlös-Refunds.",
  },
  {
    code: "FBCSTMR2",
    category: "refund",
    label: "FBA Customer Returns Fee (Non-Apparel)",
    meaning: "Retouren-Bearbeitungsgebühr Non-Apparel.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie FBCSTMR1.",
  },

  // --- FBA Reimbursements (Amazon erstattet Verlust/Schaden) ---
  {
    code: "FBNVNTRY",
    category: "reimbursement",
    label: "FBA Reimbursement Damaged",
    meaning: "Amazon erstattet beschädigte Ware (Lager-Schaden).",
    sign: "plus",
    skr03: "8400 Sonstige Erträge (Schlüssel 0 oder 9 je nach Doku)",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint:
      "Schadensersatz – nicht steuerbar (echter Schadensersatz, kein Leistungsaustausch). Im Zweifel mit StB klären, manche buchen mit USt.",
    popular: true,
  },
  {
    code: "FBAIRDW",
    category: "reimbursement",
    label: "FBA Reimbursement Damaged Warehouse",
    meaning: "Amazon erstattet im Lager beschädigte Ware.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz – wie FBNVNTRY.",
  },
  {
    code: "FBNVNTR1",
    category: "reimbursement",
    label: "FBA Reimbursement Fee Correction",
    meaning: "Korrektur einer FBA-Gebühr (Fee-Reimbursement).",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung, Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung, da Gebühr falsch berechnet war. VSt korrigieren.",
  },
  {
    code: "FBNVNTR2",
    category: "reimbursement",
    label: "FBA Reimbursement Lost",
    meaning: "Amazon erstattet im Lager verlorene Ware.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz, nicht steuerbar.",
    popular: true,
  },
  {
    code: "FBNVNTR3",
    category: "reimbursement",
    label: "FBA Reimbursement Return Adjustment",
    meaning: "Korrektur einer Retoure-Erstattung.",
    sign: "both",
    skr03: "8400 Sonstige Erträge / 8730 Erlösschmälerung (je nach Vorzeichen)",
    skr04: "4830 / 4730",
    ust: "0% / Erlös-Korrektur",
    bookingHint: "Vorzeichen prüfen – Aufwand- oder Ertragskorrektur.",
  },
  {
    code: "FBAIRCR",
    category: "reimbursement",
    label: "FBA Reimbursement Customer Return",
    meaning: "Erstattung wenn Retoure nicht in Lager zurückkam.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "FBAIRCSI",
    category: "reimbursement",
    label: "FBA Reimbursement Customer Service Issue",
    meaning: "Erstattung bei Customer-Service-Issue.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "WarehDam",
    category: "reimbursement",
    label: "Warehouse Damage",
    meaning: "Schaden im Amazon-Warehouse → Erstattung.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "WaHDamEx",
    category: "reimbursement",
    label: "Warehouse Damage Exception",
    meaning: "Ausnahme bei Warehouse-Damage-Erstattung.",
    sign: "both",
    skr03: "8400 Sonstige Erträge / Korrektur",
    skr04: "4830 / Korrektur",
    ust: "0% steuerfrei",
    bookingHint: "Vorzeichen prüfen.",
  },
  {
    code: "WRHSLST",
    category: "reimbursement",
    label: "Warehouse Lost",
    meaning: "Amazon hat Ware verloren → Erstattung.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "WaHLoMan",
    category: "reimbursement",
    label: "Warehouse Lost Manual",
    meaning: "Manuelle Warehouse-Lost-Erstattung.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "MisFrInb",
    category: "reimbursement",
    label: "Missing from Inbound",
    meaning: "Ware fehlt nach Inbound-Anlieferung – Amazon erstattet.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "MSSNGFRM",
    category: "reimbursement",
    label: "Missing from Inbound Clawback",
    meaning: "Amazon zieht eine Inbound-Erstattung wieder zurück (z.B. Ware doch gefunden).",
    sign: "minus",
    skr03: "8400 Sonstige Erträge (Korrektur)",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Aufhebung der vorherigen Erstattung.",
  },
  {
    code: "InbCarDa",
    category: "reimbursement",
    label: "Inbound Carrier Damage",
    meaning: "Versand-Schaden beim Inbound-Carrier.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "RemOrdDa",
    category: "reimbursement",
    label: "Removal Order Damaged",
    meaning: "Bei Lager-Auslagerung beschädigt.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "RemOrdLo",
    category: "reimbursement",
    label: "Removal Order Lost",
    meaning: "Bei Auslagerung verloren.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "MuChOrDa",
    category: "reimbursement",
    label: "Multichannel Order Damaged",
    meaning: "Multichannel-Order: beschädigt.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "MLTCHNNL",
    category: "reimbursement",
    label: "Multichannel Order Late",
    meaning: "Multichannel-Order: zu spät geliefert.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "MulOrdLo",
    category: "reimbursement",
    label: "Multichannel Order Lost",
    meaning: "Multichannel-Order verloren.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "SAFE-T",
    category: "reimbursement",
    label: "SAFE-T Reimbursement",
    meaning: "SAFE-T-Claim-Erstattung (bei FBM-Streit).",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },

  // --- Chargebacks ---
  {
    code: "ChargeBk",
    category: "chargeback",
    label: "Chargeback",
    meaning: "Kreditkarten-Rückbuchung durch Käufer-Bank.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung wie A-to-z.",
  },
  {
    code: "CHRGBCKR",
    category: "chargeback",
    label: "Chargeback Recovery",
    meaning: "Rückgewinnung eines Chargebacks (Streit gewonnen).",
    sign: "plus",
    skr03: "8730 Erlösschmälerungen (Korrektur)",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Aufhebung der Chargeback-Buchung.",
  },
  {
    code: "ChrgBkRe",
    category: "chargeback",
    label: "Chargeback Refund",
    meaning: "Refund eines Chargebacks.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },

  // --- Reserve ---
  {
    code: "CurrReAm",
    category: "reserve",
    label: "Current Reserve Amount",
    meaning:
      "Sicherheits-Reserve, die Amazon für eventuelle Refunds zurückhält. Lt. PayJoe-Doku: SKR03 1501 / SKR04 1301.",
    sign: "minus",
    skr03: "1501 Sonstige Vermögensgegenstände",
    skr04: "1301 Sonstige Vermögensgegenstände",
    ust: "nicht steuerbar",
    bookingHint:
      "KEIN Aufwand! Forderungs-Umbuchung: dein Geld wird nur 'eingefroren'. Buchung: 1501 (Soll) an Forderungen Amazon (Haben).",
    popular: true,
  },
  {
    code: "PrReAmBa",
    category: "reserve",
    label: "Previous Reserve Amount Balance",
    meaning: "Auflösung der Reserve aus Vorperiode.",
    sign: "plus",
    skr03: "1501 Sonstige Vermögensgegenstände (Auflösung)",
    skr04: "1301 Sonstige Vermögensgegenstände",
    ust: "nicht steuerbar",
    bookingHint: "Gegenbuchung zu CurrReAm: Forderungen Amazon (Soll) an 1501 (Haben).",
    popular: true,
  },

  // --- EPR / Verpackungsgesetz ---
  {
    code: "PRPYNBHL",
    category: "epr",
    label: "EPR Pay on Behalf eco-contribution",
    meaning:
      "Erweiterte Herstellerverantwortung (EPR): Amazon zahlt im Namen des Händlers Eco-Contribution für Verpackungen (FR), Möbel, Elektro, Textil etc. Stellt das in Rechnung.",
    sign: "minus",
    skr03: "4380 Sonstige Abgaben (Schlüssel 9 wenn USt) / 4390 Beiträge",
    skr04: "6855 Sonstige Abgaben",
    ust: "19% VSt-abziehbar",
    bookingHint:
      "Eco-Contribution für FR-Marketplace ist USt-pflichtig (Amazon Service Fee). Manche StB buchen auch auf 4900 sonstige Aufwendungen. Nicht auf Fremdleistungen!",
    popular: true,
  },
  {
    code: "PRPYNBH1",
    category: "epr",
    label: "EPR Pay on Behalf service fee",
    meaning: "EPR-Service-Gebühr (Pauschale).",
    sign: "minus",
    skr03: "4380 Sonstige Abgaben (Schlüssel 9)",
    skr04: "6855 Sonstige Abgaben",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie PRPYNBHL.",
  },
  {
    code: "CCNTRBTN",
    category: "epr",
    label: "Eco-contribution EPR FR",
    meaning: "Frankreich-spezifische Eco-Contribution.",
    sign: "minus",
    skr03: "4380 Sonstige Abgaben (Schlüssel 9)",
    skr04: "6855 Sonstige Abgaben",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie PRPYNBHL.",
  },
  {
    code: "MZNSRVCF",
    category: "epr",
    label: "Amazon EPR Service Fee FR",
    meaning: "Amazon-Service-Fee für EPR-Compliance Frankreich.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 19 = Reverse Charge)",
    skr04: "5900 Fremdleistungen",
    ust: "Reverse Charge",
    bookingHint: "Reverse Charge (FR-Sarl).",
  },

  // --- Tax / VAT ---
  {
    code: "MRKTPLCF",
    category: "tax",
    label: "Marketplace Facilitator VAT",
    meaning:
      "Amazon zieht USt für bestimmte Verkäufe ein und zahlt sie direkt ans FA (z.B. UK-B2C-Verkäufe nach Brexit, FR/IT-Importverkäufe, US-Sales-Tax).",
    sign: "both",
    skr03: "8400 Sonstige Erträge bzw. Durchlaufender Posten",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "nicht steuerbar",
    bookingHint:
      "Bei UK/US: durchlaufender Posten – Amazon führt direkt ab, du brauchst es nicht in DE-USt-Voranmeldung. Im Zweifel mit StB klären.",
    popular: true,
  },
  {
    code: "MktFaVat",
    category: "tax",
    label: "Marketplace Facilitator VAT (Variante)",
    meaning: "Alternative Bezeichnung MarketplaceFacilitatorVAT.",
    sign: "both",
    skr03: "8400 Sonstige Erträge bzw. Durchlaufender Posten",
    skr04: "4830",
    ust: "nicht steuerbar",
    bookingHint: "Wie MRKTPLCF.",
  },
  {
    code: "Tax",
    category: "tax",
    label: "Tax",
    meaning: "Allgemeine Tax-Buchung.",
    sign: "both",
    skr03: "abh. von Kontext, oft Durchlaufender Posten",
    skr04: "abh. von Kontext",
    ust: "nicht steuerbar",
    bookingHint: "Kontext beachten – mit StB klären.",
  },
  {
    code: "TXDJSTMN",
    category: "tax",
    label: "Tax Adjustment",
    meaning: "Tax-Korrektur.",
    sign: "both",
    skr03: "abh. von Kontext",
    skr04: "abh. von Kontext",
    ust: "nicht steuerbar",
    bookingHint: "Mit StB klären.",
  },
  {
    code: "TXWTHHLD",
    category: "tax",
    label: "Tax Withholding Reimbursement",
    meaning: "Erstattung einer einbehaltenen Quellensteuer.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "nicht steuerbar",
    bookingHint: "Sonstiger Ertrag.",
  },
  {
    code: "VTFLNGCH",
    category: "tax",
    label: "VAT Filing Charge",
    meaning: "Gebühr für Amazon-VAT-Filing-Service.",
    sign: "minus",
    skr03: "4955 Buchführungs-/Beratungskosten (Schlüssel 9) – alt. 3100",
    skr04: "6815 Buchführungskosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie Steuerberater-Kosten.",
  },
  {
    code: "VTRGSTRT",
    category: "tax",
    label: "VAT Registration Charge",
    meaning: "Gebühr für VAT-Registrierung in EU-Land.",
    sign: "minus",
    skr03: "4955 Buchführungs-/Beratungskosten (Schlüssel 9)",
    skr04: "6815 Buchführungskosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie VTFLNGCH.",
  },
  {
    code: "VTGSTRFN",
    category: "tax",
    label: "VAT/GST Refund for Seller Fees",
    meaning: "Erstattung der USt auf Seller-Fees (selten, z.B. nach VAT-Korrektur).",
    sign: "plus",
    skr03: "1576 Vorsteuer 19% (Korrektur)",
    skr04: "1406 Vorsteuer 19%",
    ust: "19% VSt-abziehbar",
    bookingHint: "VSt-Korrektur. Mit StB klären.",
  },

  // --- Adjustments / Korrekturen ---
  {
    code: "DJSTMNT",
    category: "adjustment",
    label: "Adjustment",
    meaning: "Allgemeine Korrektur (Vorzeichen variabel).",
    sign: "both",
    skr03: "abh. – meist 4900 Sonstige Aufwendungen (−) / 8400 Sonstige Erträge (+)",
    skr04: "abh.",
    ust: "abh. von Kontext",
    bookingHint: "Kontext anschauen, Vorzeichen entscheidet Konto.",
  },
  {
    code: "DJSTMNTF",
    category: "adjustment",
    label: "Adjustment Financial Transaction",
    meaning: "Korrektur einer finanziellen Transaktion.",
    sign: "both",
    skr03: "abh.",
    skr04: "abh.",
    ust: "abh. von Kontext",
    bookingHint: "Kontext klären.",
  },
  {
    code: "BalAdj",
    category: "adjustment",
    label: "Balance Adjustment",
    meaning: "Saldo-Anpassung.",
    sign: "both",
    skr03: "abh.",
    skr04: "abh.",
    ust: "abh. von Kontext",
    bookingHint: "Kontext klären.",
  },
  {
    code: "FDJSTMNT",
    category: "adjustment",
    label: "Fee Adjustment",
    meaning: "Gebühren-Korrektur.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Korrektur, Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung/-erhöhung.",
  },
  {
    code: "MSCDJSTM",
    category: "adjustment",
    label: "Misc Adjustment",
    meaning: "Sonstige Korrektur.",
    sign: "both",
    skr03: "abh. – meist 4900 / 8400",
    skr04: "abh.",
    ust: "abh. von Kontext",
    bookingHint: "Kontext klären.",
  },
  {
    code: "DBTDJSTM",
    category: "adjustment",
    label: "Debt Adjustment",
    meaning: "Schulden-Korrektur (Amazon-Debit).",
    sign: "both",
    skr03: "abh.",
    skr04: "abh.",
    ust: "abh. von Kontext",
    bookingHint: "Kontext klären.",
  },
  {
    code: "DBTCRTN",
    category: "adjustment",
    label: "Debt Creation",
    meaning: "Schuld erzeugt (Amazon stellt offen).",
    sign: "minus",
    skr03: "abh. (oft 3100 Fremdleistungen)",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
  {
    code: "CMMSSNCR",
    category: "adjustment",
    label: "Commission Correction",
    meaning: "Provisions-Korrektur.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Korrektur)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwands-Korrektur.",
  },
  {
    code: "RFRRLFDJ",
    category: "adjustment",
    label: "Referral Fee Adjustment",
    meaning: "Verkaufsprovisions-Korrektur.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Korrektur)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwands-Korrektur.",
  },
  {
    code: "PSTGDJST",
    category: "adjustment",
    label: "Postage Adjustment",
    meaning: "Porto-Korrektur.",
    sign: "both",
    skr03: "4730 Ausgangsfrachten (Korrektur)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten-Korrektur.",
  },
  {
    code: "VRPDFSDJ",
    category: "adjustment",
    label: "Overpaid Fees Adjustment",
    meaning: "Korrektur überzahlter Gebühren (Aufwandsminderung).",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "MDCReCor",
    category: "adjustment",
    label: "MDotCom Revenue Correction",
    meaning: "Umsatz-Korrektur.",
    sign: "both",
    skr03: "8400 / 8730",
    skr04: "4830 / 4730",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlös-Korrektur.",
  },
  {
    code: "NSubFeAd",
    category: "adjustment",
    label: "Non-Subscription Fee Adjustment",
    meaning: "Korrektur Nicht-Subscription-Gebühr.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Korrektur)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwands-Korrektur.",
  },

  // --- Inbound Defects / Unplanned Service ---
  {
    code: "NBNDDFCT",
    category: "fba",
    label: "Inbound Defect Fee (Barcode)",
    meaning: "Strafgebühr bei fehlerhaftem Inbound (z.B. Amazon-Barcode fehlt).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand mit VSt 19%.",
  },
  {
    code: "UnpServFe",
    category: "fba",
    label: "Unplanned Service Fee",
    meaning: "Ungeplante Service-Gebühr (z.B. Etikett-Nachdruck).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand mit VSt 19%.",
  },
  {
    code: "NPLNNDSR",
    category: "fba",
    label: "Unplanned Service Fee (Variante)",
    meaning: "Ungeplante Service-Gebühr (alternative Bezeichnung).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie UnpServFe.",
  },
  {
    code: "ManProFe",
    category: "fba",
    label: "Manual Processing Fee",
    meaning: "Manuelle Bearbeitungsgebühr.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand mit VSt 19%.",
  },
  {
    code: "MNLPRCSS",
    category: "fba",
    label: "Manual Processing Reimbursement",
    meaning: "Erstattung einer Manual-Processing-Fee.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "WarHPrep",
    category: "fba",
    label: "Warehouse Prep",
    meaning: "Vorbereitungsdienst (Labelling, Bagging, Bubble-Wrap).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand mit VSt 19%.",
  },
  {
    code: "WRHSPRPC",
    category: "fba",
    label: "Warehouse Prep Correction",
    meaning: "Warehouse-Prep-Korrektur.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Korrektur)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwands-Korrektur.",
  },
  {
    code: "WRHSPRPR",
    category: "fba",
    label: "Warehouse Prep Reversal",
    meaning: "Warehouse-Prep-Storno.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },

  // --- Shipping / Postage ---
  {
    code: "ShiLaPur",
    category: "fba",
    label: "Shipping Label Purchase",
    meaning: "Kauf eines Versand-Etiketts (FBM).",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "SHPPNGLB",
    category: "fba",
    label: "Shipping Label for Return",
    meaning: "Versand-Etikett für Retoure.",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "ShipServ",
    category: "fba",
    label: "Shipping Services",
    meaning: "Versanddienst-Sammelposten.",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "ShiSerRe",
    category: "fba",
    label: "Shipping Services Refund",
    meaning: "Erstattung Versanddienst.",
    sign: "plus",
    skr03: "4730 Ausgangsfrachten (Aufwandsminderung)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "RetPosBi",
    category: "fba",
    label: "Return Postage Billing",
    meaning: "Berechnung Retoure-Porto.",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "RetPosBif",
    category: "fba",
    label: "Return Postage Billing Fee",
    meaning: "Bearbeitungsgebühr für Retoure-Porto (zusätzlich zum eigentlichen Porto).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie normale FBA-Gebühr (nicht Fracht, sondern Service-Pauschale).",
  },
  {
    code: "ReturnPostageBilling",
    category: "fba",
    label: "Return Postage Billing (Voll-Variante)",
    meaning: "Vollständige Schreibweise von RetPosBi – Berechnung Retoure-Porto.",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten – wie RetPosBi.",
  },

  // --- Long-Term-Storage / Aged Inventory / Low Inventory ---
  {
    code: "LongTermStorageFee",
    category: "storage",
    label: "Long-Term Storage Fee",
    meaning: "Strafgebühr für Ware die länger als 365 Tage in FBA-Lagern liegt (zusätzlich zur monatlichen Storage Fee). Sehr teuer.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie StorFe. Tipp: Removal-Order vor 365-Tage-Marke einplanen.",
  },
  {
    code: "LTSF",
    category: "storage",
    label: "Long-Term Storage Fee (Kürzel)",
    meaning: "Kurz-Variante der Long-Term Storage Fee.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie LongTermStorageFee.",
  },
  {
    code: "AgedInvSur",
    category: "storage",
    label: "Aged Inventory Surcharge",
    meaning: "Aufschlag für Inventar, das über 271 Tage im Lager ist (gestaffelt bis 365+ Tage). Eingeführt 2023, ersetzt teilweise LTSF.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand. Lange Lagerung kostet — Stockturn beobachten.",
    popular: true,
  },
  {
    code: "AgedInventorySurcharge",
    category: "storage",
    label: "Aged Inventory Surcharge (Voll)",
    meaning: "Voll-Variante des Aged Inventory Surcharge.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie AgedInvSur.",
  },
  {
    code: "StoUtilSur",
    category: "storage",
    label: "Storage Utilization Surcharge",
    meaning: "Strafe wenn dein Lager-Utilization-Ratio über 26 Wochen Durchschnitt zu schlecht ist (zu viel Lager im Verhältnis zum Verkauf).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie Storage. Symptom für zu viel Lager-Bestand.",
  },
  {
    code: "LowInventoryFee",
    category: "fba",
    label: "Low Inventory Level Fee (LIF)",
    meaning: "Strafe wenn Lager-Coverage unter 28 Tage fällt (Risiko Out-of-Stock). Eingeführt 04/2024.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand. Vermeidung: Lieferungen früher reordern oder Pre-Stock erhöhen.",
    popular: true,
  },
  {
    code: "LIF",
    category: "fba",
    label: "Low Inventory Fee (Kürzel)",
    meaning: "Kürzel für Low Inventory Level Fee.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie LowInventoryFee.",
  },

  // --- Removal / Disposal Detail ---
  {
    code: "RemovalCompletePerUnitFee",
    category: "fba",
    label: "Removal Complete Per-Unit Fee",
    meaning: "Auslagerungsgebühr pro Einheit (zurück zum Händler).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand bei Removal-Order.",
  },
  {
    code: "DisposalCompletePerUnitFee",
    category: "fba",
    label: "Disposal Complete Per-Unit Fee",
    meaning: "Entsorgungsgebühr pro Einheit (Vernichtung statt Rücksendung).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand bei Disposal-Order. Plus: Bestandsabschreibung als Aufwand.",
  },
  {
    code: "DspsFee",
    category: "fba",
    label: "Disposal Service Fee",
    meaning: "Service-Gebühr für Entsorgungs-Order (alternative Bezeichnung).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie DispComp.",
  },

  // --- Labeling / Prep Detail ---
  {
    code: "LabelingFee",
    category: "fba",
    label: "Labeling Fee",
    meaning: "Etikettier-Gebühr (Amazon klebt FNSKU-Labels statt dir).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand. Vermeidbar wenn du selbst etikettierst.",
  },
  {
    code: "LabelFee",
    category: "fba",
    label: "Label Fee",
    meaning: "Kurz-Variante Labeling Fee.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie LabelingFee.",
  },
  {
    code: "PrepFee",
    category: "fba",
    label: "Prep Fee",
    meaning: "Vorbereitungsgebühr (Bagging, Bubble-Wrap, Polybag).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie WarHPrep.",
  },
  {
    code: "PolybagFee",
    category: "fba",
    label: "Polybag Fee",
    meaning: "Gebühr für Polybag-Verpackung durch Amazon.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "BubbleWrapFee",
    category: "fba",
    label: "Bubble Wrap Fee",
    meaning: "Luftpolsterfolien-Gebühr durch Amazon.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },

  // --- Reviews / Coupons / Lightning Deal Spezial ---
  {
    code: "ManualReviewFee",
    category: "service-fee",
    label: "Manual Review Fee",
    meaning: "Manuelle Prüfgebühr (z.B. bei Listing-Suspension oder Compliance-Review).",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand. Tritt bei Account-/Listing-Problemen auf.",
  },

  // --- Tax / Donation / Spezial ---
  {
    code: "Donation",
    category: "other",
    label: "Donation (Spende)",
    meaning: "Bei FBA Donations: Amazon spendet altes Inventar an Hilfsorganisationen statt zu entsorgen. Buchung als Sachspende.",
    sign: "both",
    skr03: "4630 Sachspenden (Schlüssel 9 oder 0 je nach Begünstigtem)",
    skr04: "6630 Sachspenden",
    ust: "19% VSt-abziehbar",
    bookingHint: "Steuerliche Sachspende. Bei gemeinnütziger Organisation: Spendenquittung anfordern, sonst USt auf Entnahmewert.",
  },
  {
    code: "DonationCert",
    category: "other",
    label: "Donation Certification",
    meaning: "Bestätigung der Spende durch Amazon.",
    sign: "plus",
    skr03: "Memo-Buchung (kein Geld-Bewegung)",
    skr04: "Memo",
    ust: "nicht steuerbar",
    bookingHint: "Reine Bestätigung — nichts zu buchen außer Bestand abgeschrieben.",
  },
  {
    code: "TaxRefund",
    category: "tax",
    label: "Tax Refund",
    meaning: "Steuer-Erstattung (z.B. zu viel einbehaltene MarketplaceFacilitator-VAT).",
    sign: "plus",
    skr03: "8400 Sonstige Erträge / Durchlaufender Posten",
    skr04: "4830",
    ust: "nicht steuerbar",
    bookingHint: "Mit StB klären — durchlaufender Posten oder Ertrag je nach Kontext.",
  },
  {
    code: "TaxDiscount",
    category: "tax",
    label: "Tax Discount",
    meaning: "Steuer-Rabatt (selten).",
    sign: "plus",
    skr03: "Mit StB klären",
    skr04: "Mit StB klären",
    ust: "nicht steuerbar",
    bookingHint: "Kontext klären.",
  },
  {
    code: "TaxDiscountAdjustment",
    category: "tax",
    label: "Tax Discount Adjustment",
    meaning: "Korrektur eines Tax Discounts.",
    sign: "both",
    skr03: "Mit StB klären",
    skr04: "Mit StB klären",
    ust: "nicht steuerbar",
    bookingHint: "Kontext klären.",
  },

  // --- Buy Box / Liquidations Detail ---
  {
    code: "LSRSPRDS",
    category: "advertising",
    label: "Liquidations Sponsored Products Disbursement",
    meaning: "Auszahlung aus Sponsored-Products-Werbung im Liquidations-Programm.",
    sign: "plus",
    skr03: "4600 Werbekosten (Aufwandsminderung)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbe-Aufwandsminderung.",
  },
  {
    code: "ReimbursementClawback",
    category: "reimbursement",
    label: "Reimbursement Clawback",
    meaning: "Amazon zieht eine zuvor erstattete Reimbursement zurück (z.B. Ware doch wiederaufgetaucht).",
    sign: "minus",
    skr03: "8400 Sonstige Erträge (Korrektur)",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Aufhebung der vorherigen Erstattung.",
  },

  // --- Inventory / Removal Spezial ---
  {
    code: "InventoryAuditAdjustment",
    category: "adjustment",
    label: "Inventory Audit Adjustment",
    meaning: "Korrektur nach Lager-Audit (kann + oder − sein).",
    sign: "both",
    skr03: "8400 Sonstige Erträge / 4900 Sonstige Aufwendungen",
    skr04: "4830 / 6300",
    ust: "abh. von Vorzeichen",
    bookingHint: "Vorzeichen prüfen.",
  },
  {
    code: "BatteryRecycling",
    category: "epr",
    label: "Battery Recycling Fee",
    meaning: "Gebühr für Batterien-Entsorgung / -Recycling (BattG / EU-Batterieverordnung).",
    sign: "minus",
    skr03: "4380 Sonstige Abgaben (Schlüssel 9)",
    skr04: "6855 Sonstige Abgaben",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie EPR-Fees.",
  },

  // --- TBYB / Trial / Liquidations ---
  {
    code: "TBYBCSTM",
    category: "fba",
    label: "TBYB Customer Return Fee",
    meaning: "Try-Before-You-Buy Retoure-Gebühr.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "TBYBRDRP",
    category: "order-fee",
    label: "TBYB Order Payment",
    meaning: "Zahlung für TBYB-Order (nach Behalten der Ware).",
    sign: "plus",
    skr03: "8400 Erlöse 19% USt",
    skr04: "4400 Erlöse 19% USt",
    ust: "19% VSt-abziehbar",
    bookingHint: "Erlös wie normaler Verkauf.",
  },
  {
    code: "TBYBTRLS",
    category: "fba",
    label: "TBYB Trial Shipment",
    meaning: "TBYB-Probesendung.",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "TRLSHPMN",
    category: "fba",
    label: "Trial Shipment",
    meaning: "Probe-Versand.",
    sign: "minus",
    skr03: "4730 Ausgangsfrachten (Schlüssel 9)",
    skr04: "6740 Ausgangsfrachten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "FBTRYBFR",
    category: "fba",
    label: "FBA Try Before You Buy Multitier",
    meaning: "TBYB-Multitier-Per-Unit-Gebühr.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "LQDTNS",
    category: "other",
    label: "Liquidations",
    meaning: "Liquidations-Programm: Amazon verkauft alte Ware an Discounter, du bekommst Restwert.",
    sign: "plus",
    skr03: "8400 Erlöse 19% USt",
    skr04: "4400 Erlöse 19% USt",
    ust: "19% VSt-abziehbar",
    bookingHint: "Erlös wie Verkauf.",
  },
  {
    code: "LQDTNSF",
    category: "other",
    label: "Liquidations Fee",
    meaning: "Gebühr für Liquidations-Service.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "LQDTNSDJ",
    category: "adjustment",
    label: "Liquidations Adjustment",
    meaning: "Liquidations-Korrektur.",
    sign: "both",
    skr03: "abh. von Vorzeichen",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },

  // --- Auszahlung / Disbursement-Variations ---
  {
    code: "PayaTAma",
    category: "payout",
    label: "Payable to Amazon",
    meaning: "Verbindlichkeit an Amazon (offener Saldo).",
    sign: "minus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit-Konto wie Auszahlung.",
  },
  {
    code: "SucChar",
    category: "payout",
    label: "Successful Charge",
    meaning: "Erfolgreicher Charge auf Saldo.",
    sign: "both",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit-Konto.",
  },
  {
    code: "FailDisb",
    category: "payout",
    label: "Failed Disbursement",
    meaning: "Fehlgeschlagene Auszahlung (Bank-Rückbuchung).",
    sign: "minus",
    skr03: "1360 Geldtransit (Korrektur)",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Storno der Auszahlung.",
  },
  {
    code: "DisbCorr",
    category: "payout",
    label: "Disbursement Correction",
    meaning: "Korrektur einer Auszahlung.",
    sign: "both",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit-Korrektur.",
  },
  {
    code: "MNLDSBRS",
    category: "payout",
    label: "Manual Disbursement",
    meaning: "Manuelle Auszahlung.",
    sign: "plus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Wie reguläre Auszahlung.",
  },
  {
    code: "TRNSFRS",
    category: "payout",
    label: "Transfers",
    meaning: "Interne Transfers zwischen Amazon-Konten.",
    sign: "both",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit.",
  },
  {
    code: "TrOFuUns",
    category: "payout",
    label: "Transfer of Funds Unsuccessful",
    meaning: "Fehlgeschlagener Transfer.",
    sign: "minus",
    skr03: "1360 Geldtransit (Korrektur)",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Storno.",
  },
  {
    code: "MCRDPST",
    category: "payout",
    label: "Micro Deposit",
    meaning: "Test-Mikrobetrag bei Bankkonto-Verifizierung.",
    sign: "both",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit – meist saldoneutral.",
  },
  {
    code: "MCRDPSTF",
    category: "payout",
    label: "Micro Deposit Failed",
    meaning: "Fehlgeschlagene Mikro-Verifizierung.",
    sign: "minus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit.",
  },

  // --- Sonstiges ---
  {
    code: "RDRCNCLL",
    category: "refund",
    label: "Order Cancellation Charge",
    meaning: "Gebühr bei Order-Stornierung durch Verkäufer.",
    sign: "minus",
    skr03: "4900 Sonstige Aufwendungen",
    skr04: "6300 Sonstige betriebliche Aufwendungen",
    ust: "0% steuerfrei",
    bookingHint: "Strafgebühr – kein Leistungsaustausch, keine USt.",
  },
  {
    code: "RDRRTRCH",
    category: "refund",
    label: "Order Retrocharge",
    meaning: "Order-Rückbelastung.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "RetChar",
    category: "refund",
    label: "Retrocharge",
    meaning: "Rückbelastung.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "RTRCHRGR",
    category: "refund",
    label: "Retrocharge Reversal",
    meaning: "Aufhebung einer Rückbelastung.",
    sign: "plus",
    skr03: "8730 Erlösschmälerungen (Korrektur)",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlös-Korrektur.",
  },
  {
    code: "BuyRe",
    category: "refund",
    label: "Buyer Recharge",
    meaning: "Käufer wird erneut belastet.",
    sign: "plus",
    skr03: "8400 Erlöse 19% USt",
    skr04: "4400 Erlöse 19% USt",
    ust: "19% VSt-abziehbar",
    bookingHint: "Erlös.",
  },
  {
    code: "PYMNTRTR",
    category: "refund",
    label: "Payment Retraction Items",
    meaning: "Zahlungs-Rückzug.",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "PrepfRef",
    category: "refund",
    label: "Prep Fee Refund",
    meaning: "Erstattung einer Prep-Gebühr.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "FRRPLCMN",
    category: "refund",
    label: "Free Replacement Refund Non-Itemized",
    meaning: "Free-Replacement (kein Item).",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung (Ersatzlieferung kostenlos).",
  },
  {
    code: "FRRPLCM1",
    category: "refund",
    label: "Free Replacement Refund Items",
    meaning: "Free-Replacement (Item-bezogen).",
    sign: "minus",
    skr03: "8730 Erlösschmälerungen",
    skr04: "4730 Erlösschmälerungen",
    ust: "Erlös-Korrektur",
    bookingHint: "Erlösminderung.",
  },
  {
    code: "CSErrIt",
    category: "refund",
    label: "CS Error Items",
    meaning: "Customer-Service-Error: Items.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz / Kulanz von Amazon.",
  },
  {
    code: "CSErrNIt",
    category: "refund",
    label: "CS Error Non-Itemized",
    meaning: "CS-Error ohne Item-Bezug.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Wie CSErrIt.",
  },
  {
    code: "IncorFeIt",
    category: "refund",
    label: "Incorrect Fees Items",
    meaning: "Falsch berechnete Gebühren-Erstattung.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "IncFeNIt",
    category: "refund",
    label: "Incorrect Fees Non-Itemized",
    meaning: "Falsch berechnete Gebühren ohne Item.",
    sign: "plus",
    skr03: "3100 Fremdleistungen (Aufwandsminderung)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "REEvalu",
    category: "adjustment",
    label: "Re-Evaluation",
    meaning: "Neubewertung.",
    sign: "both",
    skr03: "abh.",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
  {
    code: "RFNDFRDV",
    category: "advertising",
    label: "Refund for Advertiser",
    meaning: "Rückerstattung Werbebudget.",
    sign: "plus",
    skr03: "4600 Werbekosten (Aufwandsminderung)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten-Aufwandsminderung.",
  },
  {
    code: "RemCompl",
    category: "fba",
    label: "Removal Complete",
    meaning: "Auslagerungs-Order abgeschlossen.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Auslagerungs-Aufwand.",
  },
  {
    code: "DispComp",
    category: "fba",
    label: "Disposal Complete",
    meaning: "Entsorgung abgeschlossen.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Entsorgungsaufwand.",
  },
  {
    code: "ServFe",
    category: "service-fee",
    label: "Service Fee",
    meaning: "Generelle Service-Gebühr.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "SRVCF",
    category: "service-fee",
    label: "Service Fee (Variante)",
    meaning: "Service-Gebühr alternative Bezeichnung.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "PDSRVCSF",
    category: "service-fee",
    label: "Paid Services Fee",
    meaning: "Bezahlte Service-Gebühren.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "PRMMSRVC",
    category: "service-fee",
    label: "Premium Services Fee",
    meaning: "Premium-Service-Gebühren.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "RSRVTNF",
    category: "fba",
    label: "Reservation Fee",
    meaning: "Reservierungsgebühr.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand.",
  },
  {
    code: "CPCTYRSR",
    category: "fba",
    label: "Capacity Reservation Fee",
    meaning: "Lager-Kapazitäts-Reservierung.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwand wie Storage.",
  },
  {
    code: "SHPMNTST",
    category: "fba",
    label: "Shipment Settle",
    meaning: "Versand-Abrechnung.",
    sign: "both",
    skr03: "abh.",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
  {
    code: "MGNGSRVC",
    category: "fba",
    label: "Imaging Services Fee",
    meaning: "Foto-Service für Listings.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9) – alt. 3100",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbe- oder Fremdleistungs-Aufwand.",
  },
  {
    code: "MGNGSRV1",
    category: "fba",
    label: "Imaging Services",
    meaning: "Foto-Service.",
    sign: "minus",
    skr03: "4600 Werbekosten – alt. 3100",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Wie MGNGSRVC.",
  },
  {
    code: "PRMWRDRB",
    category: "reimbursement",
    label: "Prime Wardrobe Reimbursement",
    meaning: "Prime-Wardrobe-Erstattung.",
    sign: "plus",
    skr03: "8400 Sonstige Erträge",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Schadensersatz.",
  },
  {
    code: "RevReimb",
    category: "reimbursement",
    label: "Reversal Reimbursement",
    meaning: "Erstattungs-Aufhebung.",
    sign: "minus",
    skr03: "8400 Sonstige Erträge (Korrektur)",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "0% steuerfrei",
    bookingHint: "Aufhebung der Erstattung.",
  },
  {
    code: "FBNTRNTN",
    category: "fba",
    label: "FBA International Freight Shipping",
    meaning: "FBA-Inbound-Fracht international.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9) – alt. 4730",
    skr04: "5900 / 6740",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "FBNTRNT1",
    category: "tax",
    label: "FBA International Duties & Taxes",
    meaning: "Zölle und Steuern für internationale Inbound-Lieferungen.",
    sign: "minus",
    skr03: "3800 Wareneingang oder 4900 Sonstige Aufwendungen",
    skr04: "5300 / 6300",
    ust: "Reverse Charge",
    bookingHint: "Einfuhrumsatzsteuer beachten – mit StB klären.",
  },
  {
    code: "FBNTRNT2",
    category: "fba",
    label: "FBA International Freight Adjustment",
    meaning: "Internationale Fracht-Korrektur.",
    sign: "both",
    skr03: "3100 Fremdleistungen (Korrektur)",
    skr04: "5900 Fremdleistungen",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten-Korrektur.",
  },
  {
    code: "GSGLBLNB",
    category: "fba",
    label: "AGS Global Inbound Transportation",
    meaning: "Amazon-Global-Selling Inbound.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9) – alt. 4730",
    skr04: "5900 / 6740",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "FBNBNDT1",
    category: "fba",
    label: "FBA Inbound Transportation Program",
    meaning: "Partnered-Carrier-Inbound-Programm.",
    sign: "minus",
    skr03: "3100 Fremdleistungen (Schlüssel 9) – alt. 4730",
    skr04: "5900 / 6740",
    ust: "19% VSt-abziehbar",
    bookingHint: "Frachtkosten.",
  },
  {
    code: "PRFRMNCC",
    category: "advertising",
    label: "Performance Credits",
    meaning: "Werbe-Performance-Credits.",
    sign: "plus",
    skr03: "4600 Werbekosten (Aufwandsminderung)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Aufwandsminderung.",
  },
  {
    code: "PLCYVLTN",
    category: "other",
    label: "Policy Violation",
    meaning: "Strafgebühr Policy-Verstoß.",
    sign: "minus",
    skr03: "4900 Sonstige Aufwendungen",
    skr04: "6300 Sonstige betriebliche Aufwendungen",
    ust: "0% steuerfrei",
    bookingHint: "Strafe – ohne USt.",
  },
  {
    code: "CMPNSTDC",
    category: "other",
    label: "Compensated Clawback",
    meaning: "Rückforderung Kompensation.",
    sign: "minus",
    skr03: "8400 Sonstige Erträge (Korrektur)",
    skr04: "4830 Sonstige betriebliche Erträge",
    ust: "nicht steuerbar",
    bookingHint: "Aufhebung früherer Kompensation.",
  },
  {
    code: "CRTRNWRN",
    category: "refund",
    label: "Customer Return Wrong Item",
    meaning: "Kunde retourniert falsches Item.",
    sign: "both",
    skr03: "abh. (oft 4900 / 8400)",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
  {
    code: "DePaL2Fa",
    category: "payout",
    label: "Debt Payment Level 2 Failure",
    meaning: "Schulden-Zahlung Level 2 fehlgeschlagen.",
    sign: "minus",
    skr03: "1360 Geldtransit",
    skr04: "1460 Geldtransit",
    ust: "nicht steuerbar",
    bookingHint: "Geldtransit.",
  },
  {
    code: "LCLZTNRD",
    category: "other",
    label: "Localization Order Complete",
    meaning: "Lokalisierungs-Order abgeschlossen.",
    sign: "both",
    skr03: "4600 Werbekosten – alt. 3100",
    skr04: "6600",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbe-/Fremdleistungs-Aufwand.",
  },
  {
    code: "SLLRPWRD",
    category: "advertising",
    label: "Seller Powered Coupon Payment",
    meaning: "Seller-Powered-Coupon-Zahlung.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "SLLRRVWN",
    category: "advertising",
    label: "Seller Review Enrollment Payment",
    meaning: "Review-Programm-Zahlung.",
    sign: "minus",
    skr03: "4600 Werbekosten (Schlüssel 9)",
    skr04: "6600 Werbekosten",
    ust: "19% VSt-abziehbar",
    bookingHint: "Werbekosten.",
  },
  {
    code: "NNMZN",
    category: "other",
    label: "Non-Amazon",
    meaning: "Nicht-Amazon-Transaktion (z.B. externe Zahlung über Amazon).",
    sign: "both",
    skr03: "abh. von Kontext",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
  {
    code: "Other",
    category: "other",
    label: "Other",
    meaning: "Sonstige Buchung.",
    sign: "both",
    skr03: "4900 Sonstige Aufwendungen / 8400 Sonstige Erträge",
    skr04: "6300 / 4830",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
  {
    code: "THRTRNS2",
    category: "other",
    label: "Other Transaction",
    meaning: "Sonstige Transaktion.",
    sign: "both",
    skr03: "abh.",
    skr04: "abh.",
    ust: "abh.",
    bookingHint: "Kontext klären.",
  },
];

// Alle Codes zusammen
export const ALL_AMAZON_CODES: AmazonCode[] = [...PREFIX_CODES, ...SUB_CODES];

// Top-Codes für die Quick-Reference
export const POPULAR_CODES = ALL_AMAZON_CODES.filter((c) => c.popular);

// Kategorie-Labels (für UI)
export const CATEGORY_LABELS: Record<AmazonCodeCategory, string> = {
  prefix: "Haupt-Prefix",
  "service-fee": "Service-Gebühr",
  "order-fee": "Bestell-Gebühr",
  advertising: "Werbung / PPC",
  fba: "FBA / Versand",
  storage: "Lagergebühr",
  refund: "Refund / Erlös-Korrektur",
  reimbursement: "FBA-Erstattung (Schaden/Verlust)",
  chargeback: "Chargeback",
  payout: "Auszahlung / Geldtransit",
  reserve: "Sicherheits-Reserve",
  epr: "EPR / Verpackungsgesetz",
  subscription: "Abo (Pro-Account)",
  vine: "Coupon / Deal / Vine",
  tax: "Steuer / VAT",
  adjustment: "Korrektur / Adjustment",
  other: "Sonstiges",
};

// Suche
export function searchAmazonCodes(query: string): AmazonCode[] {
  if (!query.trim()) return ALL_AMAZON_CODES;
  const q = query.toLowerCase();
  return ALL_AMAZON_CODES.filter(
    (c) =>
      c.code.toLowerCase().includes(q) ||
      c.label.toLowerCase().includes(q) ||
      c.meaning.toLowerCase().includes(q) ||
      c.bookingHint.toLowerCase().includes(q),
  );
}

// Code-Lookup nach Kürzel (sucht Sub-Code wenn AMA-SG-DE-MZNFS gegeben ist)
// Fallback-Verhalten: bei unbekanntem Code wird der Prefix-Kontext + ein Heuristik-Hinweis zurückgegeben.
export function lookupAmazonCode(input: string): { prefix?: AmazonCode; sub?: AmazonCode; fallbackHint?: string } {
  const normalized = input.trim();
  const upper = normalized.toUpperCase();

  // 1) Exakten Match versuchen (case-insensitive)
  const exact = ALL_AMAZON_CODES.find((c) => c.code.toUpperCase() === upper);
  if (exact) {
    return exact.category === "prefix" ? { prefix: exact } : { sub: exact };
  }

  // 2) Prefix-Match (AMA-SG-DE-MZNFS → Prefix AMA-SG-DE + Sub MZNFS)
  const prefixMatch = PREFIX_CODES.find((p) => upper.startsWith(p.code.toUpperCase() + "-"));
  if (prefixMatch) {
    const remainder = upper.slice(prefixMatch.code.length + 1);
    const sub = SUB_CODES.find((s) => s.code.toUpperCase() === remainder);
    if (sub) return { prefix: prefixMatch, sub };

    // 3) Fuzzy-Match auf Sub-Code (Substring-Match in beide Richtungen)
    const fuzzy = findFuzzySubCode(remainder);
    if (fuzzy) {
      return {
        prefix: prefixMatch,
        sub: fuzzy,
        fallbackHint: `Code „${remainder}" nicht exakt in der Datenbank, aber Variante von „${fuzzy.code}" (${fuzzy.label}). Behandle wie unten.`,
      };
    }

    // 4) Default-Fallback: nimm Prefix-Empfehlung als Basis
    return {
      prefix: prefixMatch,
      fallbackHint: `Sub-Code „${remainder}" nicht in der Datenbank. Basierend auf dem Prefix (${prefixMatch.label}) empfehle ich die generische Buchung des Prefix unten. Bei Unsicherheit Felix fragen oder mit StB klären.`,
    };
  }

  // 5) Reine Sub-Code-Match (ohne Prefix)
  const subMatch = SUB_CODES.find((s) => s.code.toUpperCase() === upper);
  if (subMatch) return { sub: subMatch };

  // 6) Fuzzy-Match auf Sub-Code
  const fuzzy = findFuzzySubCode(upper);
  if (fuzzy) {
    return {
      sub: fuzzy,
      fallbackHint: `Code „${normalized}" nicht exakt gefunden, aber Variante von „${fuzzy.code}" (${fuzzy.label}).`,
    };
  }

  return {
    fallbackHint: `Code „${normalized}" nicht gefunden. Häufige Fall-Throughs: Service-Gebühr → Fremdleistung 3100 (SKR03) / 5900 (SKR04) mit 19 % VSt. Refund/Retoure → Erlösschmälerung 8730 / 4730. Auszahlung → Geldtransit 1360 / 1460. Schadensersatz → Sonstige Erträge 8400 / 4830 (0 % USt). Im Zweifel mit StB klären oder Felix fragen.`,
  };
}

// Fuzzy-Sub-Code-Lookup: sucht in beiden Richtungen (Code enthält Input ODER Input enthält Code)
function findFuzzySubCode(needle: string): AmazonCode | undefined {
  const n = needle.toUpperCase();
  if (n.length < 3) return undefined;
  // Direkter Substring-Match (z.B. "RetPosBif" enthält "RetPosBi")
  const containsMatch = SUB_CODES.find(
    (s) => n.includes(s.code.toUpperCase()) || s.code.toUpperCase().includes(n),
  );
  return containsMatch;
}
