project_id = "rwrjuzemkfghlziretdj"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.guide-detail]
verify_jwt = false

[functions.guide-data]
verify_jwt = false

[functions.guide-data-backfill]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.chat-felix]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.track-pageview]
verify_jwt = false

[functions.admin-stripe-stats]
verify_jwt = false

[functions.check-company-name]
verify_jwt = false

[functions.find-notare]
verify_jwt = false

[functions.check-brand]
verify_jwt = false

[functions.check-weee]
verify_jwt = false

[functions.enhance-text]
verify_jwt = false

[functions.amazon-fees-estimate]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = true

[functions.send-booking-reminders]
verify_jwt = false

